#[macro_export]
macro_rules! editor_commands {
    (@commands $callback:ident [ $($acc:tt)* ]) => {
        $callback!([ $($acc)*
            // LSP commands - server management
            $crate::lsp::commands::server::lsp_start_server,
            $crate::lsp::commands::server::lsp_stop_server,
            $crate::lsp::commands::server::lsp_stop_all_servers,
            $crate::lsp::commands::server::lsp_list_servers,
            $crate::lsp::commands::server::lsp_get_server_info,
            $crate::lsp::commands::server::lsp_restart,
            $crate::lsp::commands::server::lsp_get_logs,
            $crate::lsp::commands::server::lsp_clear_logs,
            $crate::lsp::commands::server::lsp_get_servers_for_language,
            // LSP commands - document sync
            $crate::lsp::commands::document::lsp_did_open,
            $crate::lsp::commands::document::lsp_did_change,
            $crate::lsp::commands::document::lsp_did_save,
            $crate::lsp::commands::document::lsp_did_close,
            // LSP commands - completion
            $crate::lsp::commands::completion::lsp_completion,
            $crate::lsp::commands::completion::lsp_completion_resolve,
            // LSP commands - navigation
            $crate::lsp::commands::navigation::lsp_hover,
            $crate::lsp::commands::navigation::lsp_definition,
            $crate::lsp::commands::navigation::lsp_references,
            $crate::lsp::commands::navigation::lsp_type_definition,
            $crate::lsp::commands::navigation::lsp_implementation,
            $crate::lsp::commands::navigation::lsp_declaration,
            // LSP commands - actions
            $crate::lsp::commands::actions::lsp_signature_help,
            $crate::lsp::commands::actions::lsp_rename,
            $crate::lsp::commands::actions::lsp_code_action,
            $crate::lsp::commands::actions::lsp_execute_command,
            $crate::lsp::commands::actions::lsp_prepare_rename,
            // LSP commands - formatting
            $crate::lsp::commands::formatting::lsp_format,
            $crate::lsp::commands::formatting::lsp_format_range,
            $crate::lsp::commands::formatting::lsp_format_on_type,
            // LSP commands - symbols
            $crate::lsp::commands::symbols::lsp_document_symbols,
            $crate::lsp::commands::symbols::lsp_workspace_symbols,
            // Multi-provider LSP commands
            $crate::lsp::commands::multi_provider::lsp_multi_completion,
            $crate::lsp::commands::multi_provider::lsp_multi_hover,
            $crate::lsp::commands::multi_provider::lsp_multi_definition,
            $crate::lsp::commands::multi_provider::lsp_multi_references,
            $crate::lsp::commands::multi_provider::lsp_multi_type_definition,
            $crate::lsp::commands::multi_provider::lsp_multi_implementation,
            $crate::lsp::commands::multi_provider::lsp_multi_code_action,
            // CodeLens commands
            $crate::lsp::commands::code_lens::lsp_code_lens,
            $crate::lsp::commands::code_lens::lsp_multi_code_lens,
            $crate::lsp::commands::code_lens::lsp_code_lens_resolve,
            // Semantic Tokens commands
            $crate::lsp::commands::semantic_tokens::lsp_semantic_tokens,
            $crate::lsp::commands::semantic_tokens::lsp_semantic_tokens_full,
            $crate::lsp::commands::semantic_tokens::lsp_semantic_tokens_range,
            $crate::lsp::commands::semantic_tokens::lsp_semantic_tokens_legend,
            $crate::lsp::commands::semantic_tokens::lsp_multi_semantic_tokens,
            // Document highlights commands
            $crate::lsp::commands::features::lsp_document_highlights,
            $crate::lsp::commands::features::lsp_multi_document_highlights,
            // Document links commands
            $crate::lsp::commands::features::lsp_document_links,
            $crate::lsp::commands::features::lsp_multi_document_links,
            $crate::lsp::commands::features::lsp_document_link_resolve,
            // Evaluatable expression commands
            $crate::lsp::commands::features::lsp_evaluatable_expression,
            // Selection ranges commands
            $crate::lsp::commands::features::lsp_selection_ranges,
            // Document colors commands
            $crate::lsp::commands::features::lsp_document_colors,
            $crate::lsp::commands::features::lsp_color_presentations,
            // Folding ranges commands
            $crate::lsp::commands::features::lsp_folding_ranges,
            $crate::lsp::commands::features::lsp_multi_folding_ranges,
            // Linked editing ranges commands
            $crate::lsp::commands::features::lsp_linked_editing_ranges,
            // Inlay hints commands
            $crate::lsp::commands::features::lsp_inlay_hints,
            $crate::lsp::commands::features::lsp_multi_inlay_hints,
            // Call/Type hierarchy commands
            $crate::lsp::commands::hierarchy::lsp_prepare_call_hierarchy,
            $crate::lsp::commands::hierarchy::lsp_call_hierarchy_incoming,
            $crate::lsp::commands::hierarchy::lsp_call_hierarchy_outgoing,
            $crate::lsp::commands::hierarchy::lsp_prepare_type_hierarchy,
            $crate::lsp::commands::hierarchy::lsp_type_hierarchy_supertypes,
            $crate::lsp::commands::hierarchy::lsp_type_hierarchy_subtypes,
            $crate::lsp::commands::hierarchy::lsp_multi_prepare_call_hierarchy,
            $crate::lsp::commands::hierarchy::lsp_multi_prepare_type_hierarchy,
            // LSP autodetect commands
            $crate::lsp::commands::autodetect::lsp_detect_servers,
            $crate::lsp::commands::autodetect::lsp_get_installed_servers,
            // Debugger commands
            $crate::dap::commands::debug_start_session,
            $crate::dap::commands::debug_stop_session,
            $crate::dap::commands::debug_get_sessions,
            $crate::dap::commands::debug_get_session_state,
            $crate::dap::commands::debug_set_breakpoints,
            $crate::dap::commands::debug_set_function_breakpoints,
            $crate::dap::commands::debug_toggle_breakpoint,
            $crate::dap::commands::debug_get_breakpoints,
            $crate::dap::commands::debug_continue,
            $crate::dap::commands::debug_pause,
            $crate::dap::commands::debug_step_over,
            $crate::dap::commands::debug_step_into,
            $crate::dap::commands::debug_step_out,
            $crate::dap::commands::debug_step_back,
            $crate::dap::commands::debug_reverse_continue,
            $crate::dap::commands::debug_restart,
            $crate::dap::commands::debug_get_threads,
            $crate::dap::commands::debug_get_stack_trace,
            $crate::dap::commands::debug_get_scopes,
            $crate::dap::commands::debug_get_variables,
            $crate::dap::commands::debug_expand_variable,
            $crate::dap::commands::debug_expand_variable_paged,
            $crate::dap::commands::debug_evaluate,
            $crate::dap::commands::debug_set_variable,
            $crate::dap::commands::debug_set_active_thread,
            $crate::dap::commands::debug_set_active_frame,
            $crate::dap::commands::debug_get_active_thread,
            $crate::dap::commands::debug_get_active_frame,
            $crate::dap::commands::debug_get_capabilities,
            $crate::dap::commands::debug_disassemble,
            $crate::dap::commands::debug_read_memory,
            $crate::dap::commands::debug_write_memory,
            $crate::dap::commands::debug_step_instruction,
            $crate::dap::commands::debug_set_instruction_breakpoint,
            $crate::dap::commands::debug_remove_instruction_breakpoint,
            $crate::dap::commands::debug_set_data_breakpoints,
            $crate::dap::commands::debug_set_exception_breakpoints,
            $crate::dap::commands::debug_completions,
            $crate::dap::commands::debug_restart_frame,
            $crate::dap::commands::debug_goto_targets,
            $crate::dap::commands::debug_goto,
            $crate::dap::commands::debug_step_in_targets,
            $crate::dap::commands::debug_step_in_target,
            $crate::dap::commands::debug_terminate_threads,
            $crate::dap::commands::debug_set_expression,
            $crate::dap::commands::debug_cancel_request,
            $crate::dap::commands::debug_loaded_sources,
            $crate::dap::commands::debug_source,
            $crate::dap::commands::debug_exception_info,
            $crate::dap::commands::debug_data_breakpoint_info,
            $crate::dap::commands::debug_modules,
            $crate::dap::commands::debug_terminate,
            $crate::dap::commands::debug_disconnect,
            $crate::dap::commands::debug_step_into_target,
            $crate::dap::commands::debug_evaluate_repl,
            // Watch expression commands
            $crate::dap::commands::debug_add_watch,
            $crate::dap::commands::debug_remove_watch,
            $crate::dap::commands::debug_update_watch,
            $crate::dap::commands::debug_get_watches,
            $crate::dap::commands::debug_evaluate_watches,
            $crate::dap::commands::debug_clear_watches,
            // Debug adapter autodetect commands
            $crate::dap::commands::debug_detect_adapters,
            $crate::dap::commands::debug_get_installed_adapters,
            // Toolchain commands
            $crate::toolchain::commands::toolchain_detect_all,
            $crate::toolchain::commands::toolchain_detect_node,
            $crate::toolchain::commands::toolchain_detect_python,
            $crate::toolchain::commands::toolchain_detect_rust,
            $crate::toolchain::commands::toolchain_detect_project,
            $crate::toolchain::commands::toolchain_set_project,
            $crate::toolchain::commands::toolchain_get_project,
            $crate::toolchain::commands::toolchain_clear_cache,
            $crate::toolchain::commands::toolchain_get_env_for_project,
            // Formatter commands
            $crate::formatter::commands::formatter_format,
            $crate::formatter::commands::formatter_format_with,
            $crate::formatter::commands::formatter_detect_config,
            $crate::formatter::commands::formatter_check_available,
            $crate::formatter::commands::formatter_get_parser,
            // Language selector commands
            $crate::language_selector::language_detect_from_path,
            $crate::language_selector::language_detect_with_confidence,
            $crate::language_selector::language_get_all,
            $crate::language_selector::language_get_by_id,
            $crate::language_selector::language_get_by_extension,
            // Editor feature commands
            $crate::editor::folding::compute_folding_ranges,
            $crate::editor::folding::get_breadcrumb_path,
            $crate::editor::folding::get_sticky_scroll_lines,
            $crate::editor::symbols::get_workspace_symbols,
            $crate::editor::snippets::expand_snippet,
            $crate::editor::inline_diff::compute_inline_diff,
            // Refactoring commands
            $crate::editor::refactoring::rename_across_files,
            $crate::editor::refactoring::extract_variable,
            $crate::editor::refactoring::extract_method,
        ])
    };
}
